package com.neomango.notification.entity;

public enum NotificationType {
	TEAM_APPLICATION_CREATED,
	TEAM_APPLICATION_APPROVED,
	TEAM_APPLICATION_REJECTED,
	TEAM_MEMBER_JOINED,
	TEAM_MEMBER_LEFT,
	TEAM_MEMBER_KICKED,
	TEAM_OWNER_DELEGATED
}
